"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const { createHarness, FakeSpeechRecognition } = require("./helpers/harness");

function withHarness(fn) { return () => { const h=createHarness();try{return fn(h)}finally{h.close()} }; }
function setValidPlayers(state) { state.mode="original";state.players=[{id:"p1",name:"Alex"},{id:"p2",name:"Blair"}]; }
function activeQuestion(h) {
  const state=h.api.getState();setValidPlayers(state);state.questionSeconds=15;
  state.game={players:state.players.map(p=>({...p,correct:0,wrong:0,timeout:0,strikes:0,eliminated:false})),startingCount:2,idx:0,qnum:0,used:[],current:null,answered:false,started:Date.now(),speechLog:[],lastSpeechLog:[],showdown:false,lastOutcomeDetail:""};
  h.api.question();return state;
}

test("setup voice routes Multiplayer and Solo",()=>{
  const cases=[["multiplayer","original","difficulty",false],["solo","solo","difficulty",false]];
  for(const [phrase,mode,screen,quick] of cases){const h=createHarness();try{h.api.go("mode");h.timers.advance(220);h.speak(phrase);const s=h.api.getState();assert.equal(s.mode,mode,phrase);assert.equal(s.screen,screen,phrase);assert.equal(s.quick,quick,phrase)}finally{h.close()}}
});

test("Choose Game Type exposes only Multiplayer and Solo",withHarness(h=>{
  h.api.mode();
  assert.deepEqual([...h.document.querySelectorAll("[data-mode]")].map(x=>x.textContent.trim()),["MULTIPLAYER","SOLO"]);
}));

test("legacy game routes require Content Packs while Solo still bypasses Who's In",()=>{
  for(const mode of ["original"]){const h=createHarness();try{const s=h.api.getState();h.api.mode();h.click(`[data-mode="${mode}"]`);h.timers.advance(220);assert.equal(s.screen,"difficulty");h.click("#cont");h.timers.advance(220);assert.equal(s.screen,"packs");h.click("#continuePacks");assert.equal(s.screen,"players");assert.notEqual(s.screen,"fun")}finally{h.close()}}
  const h=createHarness();try{const s=h.api.getState();s.players=[];h.api.mode();h.click('[data-mode="solo"]');h.timers.advance(220);assert.equal(s.screen,"difficulty");h.click("#cont");assert.equal(s.screen,"packs");h.timers.advance(220);h.click("#continuePacks");assert.equal(s.screen,"ready");assert.equal(s.players.length,1);assert.ok(s.players[0].name.trim())}finally{h.close()}
});

test("Who’s In removes the redundant subtitle and Game Settings has two primary groups",withHarness(h=>{
  const s=h.api.getState();setValidPlayers(s);h.api.players();assert.equal(h.document.querySelector(".roster-sub"),null);assert.ok(!h.document.body.textContent.includes("ENTER THE CONTENDERS"));
  h.api.time();assert.deepEqual([...h.document.querySelectorAll(".game-time-label")].map(x=>x.textContent.trim()),["ANSWER TIME","GAME LENGTH"]);assert.equal(h.document.querySelectorAll(".game-time-card").length,2);
}));

test("Original and Work Edition use varied controlled question mixes",withHarness(h=>{
  const s=h.api.getState();s.game={used:[],recentCategories:[]};h.window.Math.random=()=>0;
  s.mode="original";const original=[h.api.pickQuestion(),h.api.pickQuestion(),h.api.pickQuestion()];assert.ok(original.every(q=>q.edition!=="work"));assert.notEqual(original[0].cat,original[1].cat);
  s.game={used:[],recentCategories:[]};s.mode="work";const work=[h.api.pickQuestion(),h.api.pickQuestion(),h.api.pickQuestion()],workCats=["Transportation","Logic & Decoding","Practical Math","I Should Have Known That","Movies & TV","Music","Geography","History","Pop Culture","General Knowledge"];assert.ok(work.every(q=>workCats.includes(q.cat)));assert.ok(work.some(q=>q.edition==="work"));assert.notEqual(work[0].cat,work[1].cat);
}));

test("visible difficulty drives stable-ID question selection",withHarness(h=>{
 const s=h.api.getState();s.mode="original";s.game={used:[],recentCategories:[]};h.window.Math.random=()=>0;s.difficulty="kids";const kids=h.api.pickQuestion();assert.match(kids.difficulty,/^kids-/);assert.match(kids.id,/^los-/);s.game={used:[],recentCategories:[]};s.difficulty="hard";const hard=h.api.pickQuestion();assert.ok(["medium","hard","savage"].includes(hard.difficulty));assert.notEqual(hard.id,kids.id)
}));

test("Work industry selection and Continue work by voice",withHarness(h=>{const s=h.api.getState();s.mode="work";h.api.go("industry");h.timers.advance(220);h.speak("Healthcare");assert.equal(s.industry,"Healthcare");h.speak("continue");assert.equal(s.screen,"difficulty")}));
test("difficulty selection and Continue work by voice",withHarness(h=>{const s=h.api.getState();s.mode="work";h.api.go("difficulty");h.timers.advance(220);h.speak("hard");assert.equal(s.difficulty,"hard");h.speak("continue");assert.equal(s.screen,"packs")}));

test("Back follows the setup transition map",()=>{
  const cases=[["mode","home"],["industry","mode"],["fun","difficulty"],["packs","home"],["players","packs"],["time","players"],["ready","players"]];
  for(const [from,to] of cases){const h=createHarness();try{const s=h.api.getState();setValidPlayers(s);s.screen=from;({mode:h.api.mode,industry:h.api.industry,fun:h.api.fun,packs:h.api.packs,players:h.api.players,time:h.api.time,ready:h.api.ready}[from])();h.speak("back");assert.equal(s.screen,to,from)}finally{h.close()}}
});

test("Continue advances Game Setup through Game Mix and Who's In to one handoff",withHarness(h=>{const s=h.api.getState();setValidPlayers(s);s.screen="setup";h.api.setup();h.speak("continue");assert.equal(s.screen,"packs");h.timers.advance(220);h.speak("continue");assert.equal(s.screen,"players");h.timers.advance(220);h.speak("continue");assert.equal(s.screen,"ready");h.timers.advance(30000);assert.equal(s.screen,"ready");h.click("#showtimeStart");assert.equal(s.screen,"handoff");assert.ok(s.game)}));

test("Exit voice command returns every setup screen Home without starting a game",()=>{
  for(const screen of ["mode","industry","difficulty","fun","packs","players","time","ready"]){const h=createHarness();try{const s=h.api.getState();setValidPlayers(s);s.screen=screen;({mode:h.api.mode,industry:h.api.industry,difficulty:h.api.difficulty,fun:h.api.fun,packs:h.api.packs,players:h.api.players,time:h.api.time,ready:h.api.ready}[screen])();h.speak("exit game");assert.equal(s.screen,"home",screen);assert.equal(s.game,null)}finally{h.close()}}
});

test("category Select All, Clear All, Skip, and aliases retain intended semantics",()=>{
  for(const [phrase,expected] of [["select all",11],["clear all",0],["skip",0]]){const h=createHarness();try{const s=h.api.getState();s.screen="fun";s.categories=phrase==="clear all"?["Music"]:[];h.api.fun();h.speak(phrase);assert.equal(s.categories.length,expected,phrase);if(phrase==="skip")assert.equal(s.screen,"packs")}finally{h.close()}}
  const h=createHarness();try{const s=h.api.getState();s.screen="fun";s.categories=[];h.api.fun();for(const phrase of ["movies and tv","food","transport"])h.speak(phrase);assert.deepEqual(Array.from(s.categories),["Movies & TV","Food & Drink","Transportation"])}finally{h.close()}
});

test("player voice variants add, assign, rename, and remove by name or number",()=>{
  const commands=[["add another player",["Alex","Blair","Player 3"]],["player named Casey",["Alex","Blair","Casey"]],["put Casey in",["Alex","Blair","Casey"]],["player one is Casey",["Casey","Blair"]],["make player two Casey",["Alex","Casey"]],["rename Blair to Casey",["Alex","Casey"]],["delete player two",["Alex"]],["remove Blair",["Alex"]]];
  for(const [command,names] of commands){const h=createHarness();try{const s=h.api.getState();setValidPlayers(s);s.screen="players";h.api.players();h.speak(command);assert.deepEqual(Array.from(s.players,p=>p.name),names,command)}finally{h.close()}}
});

test("bare Player and Player Two commands do not mutate the roster",()=>{for(const command of ["player","player two"]){const h=createHarness();try{const s=h.api.getState();setValidPlayers(s);s.screen="players";h.api.players();h.speak(command);assert.deepEqual(Array.from(s.players,p=>p.name),["Alex","Blair"])}finally{h.close()}}});
test("player data mutations and Continue wait for final speech",withHarness(h=>{const s=h.api.getState();setValidPlayers(s);s.screen="players";h.api.players();h.speak("add player Casey",{final:false});assert.deepEqual(Array.from(s.players,p=>p.name),["Alex","Blair"]);h.speak("add player Casey",{final:true});assert.deepEqual(Array.from(s.players,p=>p.name),["Alex","Blair","Casey"]);h.speak("continue",{final:false});assert.equal(s.screen,"players");h.speak("continue",{final:true});assert.equal(s.screen,"ready")}));

test("recognition alternatives route the first actionable transcript",withHarness(h=>{const s=h.api.getState();h.api.go("mode");h.timers.advance(220);h.speak("unrelated noise",{alternatives:["multiplayer"]});assert.equal(s.mode,"original");assert.equal(s.screen,"difficulty")}));
test("recognition onend restarts listening with the current screen context",withHarness(h=>{const s=h.api.getState();h.api.go("mode");h.timers.advance(220);const first=h.recognition(),count=FakeSpeechRecognition.instances.length;first.end();assert.equal(h.recognition(),null);h.timers.advance(25);assert.equal(FakeSpeechRecognition.instances.length,count+1);h.speak("solo");assert.equal(s.mode,"solo");assert.equal(s.screen,"difficulty")}));
test("no-speech recognition termination self-heals",withHarness(h=>{const first=h.recognition(),count=FakeSpeechRecognition.instances.length;first.error("no-speech");first.end();h.timers.advance(25);assert.equal(FakeSpeechRecognition.instances.length,count+1);assert.ok(h.recognition().started)}));
test("healthy recognition remains active across setup navigation",withHarness(h=>{const first=h.recognition(),count=FakeSpeechRecognition.instances.length;h.api.go("mode");assert.equal(h.recognition(),first);assert.equal(FakeSpeechRecognition.instances.length,count);h.timers.advance(220);h.speak("family");assert.equal(h.api.getState().screen,"difficulty");assert.equal(h.recognition(),first)}));
test("same-screen rerenders do not restart healthy recognition",withHarness(h=>{const s=h.api.getState(),first=h.recognition(),count=FakeSpeechRecognition.instances.length;s.screen="fun";s.categories=[];h.api.fun();h.speak("music");h.speak("sports");assert.equal(h.recognition(),first);assert.equal(FakeSpeechRecognition.instances.length,count)}));
test("the first command immediately after navigation uses the updated context",withHarness(h=>{const s=h.api.getState(),first=h.recognition();s.categories=[];h.api.go("fun");assert.equal(h.recognition(),first);h.speak("music");assert.deepEqual(Array.from(s.categories),["Music"]);assert.equal(s.screen,"fun")}));
test("aborted recognition termination recovers automatically",withHarness(h=>{const first=h.recognition(),count=FakeSpeechRecognition.instances.length;first.error("aborted");first.end();h.timers.advance(25);assert.equal(FakeSpeechRecognition.instances.length,count+1);assert.ok(h.recognition().started)}));
test("service-not-allowed blocks automatic restart",withHarness(h=>{const first=h.recognition(),count=FakeSpeechRecognition.instances.length;first.error("service-not-allowed");first.end();h.timers.advance(5000);assert.equal(h.recognition(),null);assert.equal(FakeSpeechRecognition.instances.length,count)}));
test("Voice Off remains off when the stopped recognizer later ends",withHarness(h=>{const s=h.api.getState();s.screen="time";h.api.time();const first=h.recognition(),count=FakeSpeechRecognition.instances.length;h.click("#voiceOff");first.end();h.timers.advance(5000);assert.equal(s.voiceOn,false);assert.equal(h.recognition(),null);assert.equal(FakeSpeechRecognition.instances.length,count)}));
test("Voice On explicitly recovers after service permission block",withHarness(h=>{const s=h.api.getState(),first=h.recognition(),count=FakeSpeechRecognition.instances.length;first.error("service-not-allowed");first.end();s.screen="time";h.api.time();assert.equal(h.recognition(),null);h.click("#voiceOn");assert.equal(s.voiceOn,true);assert.ok(h.recognition()?.started);assert.equal(FakeSpeechRecognition.instances.length,count+1)}));
test("stale callbacks from an old recognition generation are ignored",withHarness(h=>{const s=h.api.getState(),old=h.recognition();h.api.go("mode");h.timers.advance(220);old.end();h.timers.advance(25);const current=h.recognition(),count=FakeSpeechRecognition.instances.length;assert.notEqual(current,old);old.emit("multiplayer");old.error("not-allowed");old.end();h.timers.advance(1000);assert.equal(s.screen,"mode");assert.equal(h.recognition(),current);assert.equal(FakeSpeechRecognition.instances.length,count);h.speak("multiplayer");assert.equal(s.screen,"difficulty")}));
test("recognition start failures retry with one bounded backoff chain",withHarness(h=>{const old=h.recognition(),before=FakeSpeechRecognition.instances.length;FakeSpeechRecognition.startFailures=2;old.end();h.timers.advance(25);assert.equal(FakeSpeechRecognition.instances.length,before+1);assert.equal(h.recognition(),null);h.timers.advance(99);assert.equal(FakeSpeechRecognition.instances.length,before+1);h.timers.advance(1);assert.equal(FakeSpeechRecognition.instances.length,before+2);h.timers.advance(249);assert.equal(FakeSpeechRecognition.instances.length,before+2);h.timers.advance(1);assert.equal(FakeSpeechRecognition.instances.length,before+3);assert.ok(h.recognition().started)}));
test("interim setup action followed by its final transcript executes once",withHarness(h=>{const s=h.api.getState();s.screen="fun";s.categories=[];h.api.fun();const first=h.recognition(),count=FakeSpeechRecognition.instances.length;first.emit("music",{final:false});first.emit("music",{final:true});assert.deepEqual(Array.from(s.categories),["Music"]);assert.equal(h.recognition(),first);assert.equal(FakeSpeechRecognition.instances.length,count)}));
test("question answering works through the persistent recognizer onresult path",withHarness(h=>{const s=activeQuestion(h),current=h.recognition();s.game.current={q:"What planet is known as the Red Planet?",a:"Mars"};s.game.answered=false;current.emit("Mars",{final:true,confidence:.99});assert.equal(s.game.players[0].correct,1);assert.equal(s.game.answered,true)}));
test("low-confidence exact setup commands execute without a confidence threshold",()=>{
  const cases=[
    {screen:"mode",phrase:"family",assert:s=>assert.equal(s.screen,"difficulty")},
    {screen:"difficulty",phrase:"hard",assert:s=>assert.equal(s.difficulty,"hard")},
    {screen:"fun",phrase:"select all",setup:s=>{s.categories=[]},assert:s=>assert.equal(s.categories.length,11)},
    {screen:"fun",phrase:"clear all",setup:s=>{s.categories=["Music"]},assert:s=>assert.equal(s.categories.length,0)},
    {screen:"fun",phrase:"music",setup:s=>{s.categories=[]},assert:s=>assert.deepEqual(Array.from(s.categories),["Music"])}
  ];
  for(const c of cases){const h=createHarness();try{const s=h.api.getState();s.screen=c.screen;c.setup?.(s);h.api[c.screen]();h.speak(c.phrase,{final:false,confidence:.01});c.assert(s)}finally{h.close()}}
});
test("navigation interim waits and its final result operates exactly one setup screen",withHarness(h=>{const s=h.api.getState();s.screen="difficulty";h.api.difficulty();const r=h.recognition();r.emit("continue",{final:false,confidence:.01});assert.equal(s.screen,"difficulty");r.emit("continue",{final:true,confidence:.01});assert.equal(s.screen,"packs");h.timers.advance(220);assert.equal(s.screen,"packs")}));
test("a voice navigation command arriving in the new locked context executes once after unlock",withHarness(h=>{const s=h.api.getState();h.api.go("difficulty");const r=h.recognition();r.emit("continue",{final:false,confidence:.01});r.emit("continue",{final:true,confidence:.01});assert.equal(s.screen,"difficulty");h.timers.advance(220);assert.equal(s.screen,"packs");h.timers.advance(220);assert.equal(s.screen,"packs")}));
test("Resume interim waits and its final resumes without answering the question",withHarness(h=>{const s=activeQuestion(h);s.game.current={q:"What planet?",a:"Mars"};s.game.answered=false;h.api.pauseGame();const r=h.recognition();r.emit("resume",{final:false,confidence:.01});assert.equal(s.screen,"paused");r.emit("resume",{final:true,confidence:.01});assert.equal(s.screen,"question");assert.equal(s.game.answered,false);assert.equal(s.game.players[0].wrong,0)}));
test("voice diagnostics distinguish transcript, confidence, execution, and rejection",withHarness(h=>{const s=h.api.getState();s.screen="difficulty";h.api.difficulty();h.speak("hard",{final:true,confidence:.03});h.speak("definitely not a command",{final:true,confidence:.17});const d=h.api.getVoiceDiagnostics();assert.ok(d.some(x=>x.stage==="recognition-started"));assert.ok(d.some(x=>x.stage==="transcript-received"&&x.text==="hard"&&x.confidence===.03));assert.ok(d.some(x=>x.stage==="command-executed"&&x.command==="difficulty hard"));assert.ok(d.some(x=>x.stage==="command-rejected"&&x.reason==="no-command-match"))}));
test("Food & Drink voice aliases select the canonical category additively",()=>{for(const phrase of ["Food & Drink","Food and Drink","Food"]){const h=createHarness();try{const s=h.api.getState();s.screen="fun";s.categories=["Music"];h.api.fun();const r=h.recognition();r.emit(phrase,{final:false,confidence:.01});r.emit(phrase,{final:true,confidence:.01});assert.deepEqual(Array.from(s.categories),["Music","Food & Drink"],phrase)}finally{h.close()}}});
test("History and decade aliases select their canonical categories once",()=>{for(const [phrase,expected] of [["History","History"],["90s & 2000s","90s & 2000s"],["90s and 2000s","90s & 2000s"],["Nineties and Two Thousands","90s & 2000s"]]){const h=createHarness();try{const s=h.api.getState();s.screen="fun";s.categories=["Music"];h.api.fun();const r=h.recognition();r.emit(phrase,{final:false,confidence:.02});r.emit(phrase,{final:true,confidence:.02});assert.deepEqual(Array.from(s.categories),["Music",expected],phrase)}finally{h.close()}}});
test("all Game Settings duration choices use the canonical voice action",()=>{for(const [phrase,minutes] of [["5 Minutes",5],["Five Minutes",5],["Set Game Length to 5 Minutes",5],["Game Length 5 Minutes",5],["10 Minutes",10],["Fifteen Minutes",15],["20 Minutes",20]]){const h=createHarness();try{const s=h.api.getState();s.screen="time";s.quick=true;h.api.time();const r=h.recognition();r.emit(phrase,{final:false,confidence:.01});assert.equal(s.duration,minutes,phrase);assert.equal(s.quick,false,phrase);r.emit(phrase,{final:true,confidence:.01});assert.equal(s.duration,minutes,phrase)}finally{h.close()}}});
test("exact interim setup execution has no intentional application-side delay",withHarness(h=>{const s=h.api.getState();s.screen="time";h.api.time();const r=h.recognition();r.emit("Five Minutes",{final:false,confidence:.01});assert.equal(s.duration,5);const d=h.api.getVoiceDiagnostics(),received=d.find(x=>x.stage==="transcript-received"&&x.text==="Five Minutes"),matched=d.find(x=>x.stage==="command-matched"&&x.command==="duration 5"),executed=d.find(x=>x.stage==="command-executed"&&x.command==="duration 5");assert.ok(received&&matched&&executed);assert.ok(matched.monoAt-received.monoAt<5);assert.ok(executed.monoAt-received.monoAt<5);r.emit("Five Minutes",{final:true,confidence:.01});assert.equal(s.duration,5);assert.ok(h.api.getVoiceDiagnostics().some(x=>x.reason==="final-after-handled-interim"))}));
test("developer voice latency mode records browser activity through command execution",()=>{const h=createHarness({voiceLatency:true});try{const s=h.api.getState();s.screen="difficulty";h.api.difficulty();const r=h.recognition();r.audioStart();r.soundStart();r.speechStart();r.emit("hard",{final:false,confidence:.2});const d=h.api.getVoiceDiagnostics(),stages=d.map(x=>x.stage);for(const stage of ["recognition-started","audio-start","sound-start","speech-start","first-interim-transcript","command-matched","command-executed"])assert.ok(stages.includes(stage),stage);assert.ok(h.document.getElementById("voiceLatencyPanel"));assert.equal(s.difficulty,"hard")}finally{h.close()}});

test("same-screen category and player rerenders retain active voice control",withHarness(h=>{const s=h.api.getState();s.screen="fun";s.categories=[];h.api.fun();h.speak("music");h.speak("sports");assert.deepEqual(Array.from(s.categories),["Music","Sports"]);s.screen="players";setValidPlayers(s);h.api.players();h.speak("add player Casey");h.speak("remove Casey");assert.deepEqual(Array.from(s.players,p=>p.name),["Alex","Blair"])}));
test("duplicate category interim and final transcripts remain idempotent",withHarness(h=>{const s=h.api.getState();s.screen="fun";s.categories=[];h.api.fun();h.speak("music",{final:false});h.speak("music",{final:true});assert.deepEqual(Array.from(s.categories),["Music"])}));
test("duplicate final player transcripts perform one mutation",withHarness(h=>{const s=h.api.getState();setValidPlayers(s);s.screen="players";h.api.players();h.speak("add player Casey");h.speak("add player Casey");assert.deepEqual(Array.from(s.players,p=>p.name),["Alex","Blair","Casey"])}));

test("voice lookup after category rerender never clicks a detached old button",withHarness(h=>{const s=h.api.getState();s.screen="fun";s.categories=[];h.api.fun();const oldSports=h.document.querySelector('[data-cat="Sports"]');let detachedClicks=0;oldSports.addEventListener("click",()=>detachedClicks++);h.click('[data-cat="Music"]');assert.equal(oldSports.isConnected,false);h.speak("Sports");assert.equal(detachedClicks,0);assert.deepEqual(Array.from(s.categories),["Music","Sports"])}));

test("player add rename delete and Continue survive consecutive rerenders",withHarness(h=>{const s=h.api.getState();setValidPlayers(s);s.screen="players";h.api.players();h.speak("add player Casey");h.speak("rename Casey to Dana");h.speak("remove Dana");h.speak("continue",{final:true});assert.deepEqual(Array.from(s.players,p=>p.name),["Alex","Blair"]);assert.equal(s.screen,"ready")}));

test("Game Settings rerender uses current controls for the next voice command",withHarness(h=>{const s=h.api.getState();s.screen="time";h.api.time();h.speak("10 seconds");assert.equal(s.questionSeconds,10);h.speak("volume up");assert.ok(Math.abs(s.volume-.75)<1e-9);assert.equal(Number(h.document.querySelector("#vol").value),.75)}));

test("exact setup controls remain interim-responsive while fuzzy wrappers remain final-only",withHarness(h=>{const s=h.api.getState();h.api.go("mode");h.timers.advance(220);h.speak("choose multiplayer game",{final:false});assert.equal(s.screen,"mode");assert.equal(s.mode,"original");h.speak("multiplayer",{final:false});assert.equal(s.screen,"difficulty")}));

test("fuzzy visible-control matching activates only on final speech",withHarness(h=>{const s=h.api.getState();s.mode="solo";h.api.go("mode");h.timers.advance(220);h.speak("choose multiplayer game",{final:false});assert.equal(s.screen,"mode");h.speak("choose multiplayer game",{final:true});assert.equal(s.mode,"original");assert.equal(s.screen,"difficulty")}));

test("question answers win before an identically labeled visible control",withHarness(h=>{const s=activeQuestion(h);s.game.current={q:"What planet is known as the Red Planet?",a:"Mars"};s.game.answered=false;const button=h.document.createElement("button");button.textContent="Mars";let clicks=0;button.onclick=()=>clicks++;h.document.body.appendChild(button);h.speak("Mars",{final:true,confidence:.4});assert.equal(s.game.players[0].correct,1);assert.equal(clicks,0)}));
test("navigation lock rejects a second transition until its 220ms window expires",withHarness(h=>{const s=h.api.getState();h.api.go("mode");h.api.go("difficulty");assert.equal(s.screen,"mode");h.timers.advance(219);h.api.go("difficulty");assert.equal(s.screen,"mode");h.timers.advance(1);h.api.go("difficulty");assert.equal(s.screen,"difficulty")}));

test("active-game persistence round trip restores settings and turn at a safe question checkpoint",withHarness(h=>{const s=activeQuestion(h);s.categories=["Music"];s.industry="Healthcare";s.difficulty="hard";s.game.players[0].strikes=2;s.game.idx=1;s.game.qnum=6;s.game.used=["q1"];h.api.saveActiveGame();s.categories=[];s.industry="";s.difficulty="easy";s.game=null;h.api.resumeSavedGame();assert.equal(s.screen,"handoff");assert.equal(s.categories[0],"Music");assert.equal(s.industry,"Healthcare");assert.equal(s.difficulty,"hard");assert.equal(s.game.idx,1);assert.equal(s.game.players[0].strikes,2);assert.equal(s.game.qnum,6);assert.deepEqual(Array.from(s.game.used),["q1"]);assert.equal(s.game.current,null);assert.equal(s.game.answered,false)}));
test("protected question behavior remains routed through fake recognition",withHarness(h=>{const s=activeQuestion(h);s.game.current={q:"What planet?",a:"Mars"};s.game.answered=false;h.speak("Mars",{final:true,confidence:.4});assert.equal(s.game.players[0].correct,1);assert.equal(s.game.answered,true)}));

test("permission denial blocks restart until explicit Voice On action",withHarness(h=>{const first=h.recognition(),count=FakeSpeechRecognition.instances.length;first.error("not-allowed");first.end();h.timers.advance(100);assert.equal(h.recognition(),null);assert.equal(FakeSpeechRecognition.instances.length,count);const s=h.api.getState();s.screen="time";h.api.time();assert.equal(h.recognition(),null);h.click("#voiceOn");assert.ok(h.recognition());assert.equal(FakeSpeechRecognition.instances.length,count+1)}));

test("leaving a Question cancels countdown, timeout, and strike work",withHarness(h=>{const s=activeQuestion(h),abandoned=s.game,remaining=s.game.questionRemaining;h.speak("exit game");assert.equal(s.screen,"home");h.timers.advance(12000);assert.equal(abandoned.questionRemaining,remaining);assert.equal(abandoned.players[0].timeout,0);assert.equal(abandoned.players[0].strikes,0);assert.equal(s.screen,"home")}));

test("leaving a Result cancels delayed advancement",withHarness(h=>{const s=activeQuestion(h);h.api.finish("correct");assert.equal(s.screen,"result");h.speak("exit game");assert.equal(s.screen,"home");assert.doesNotThrow(()=>h.timers.advance(6000));assert.equal(s.screen,"home");assert.equal(s.game,null)}));

test("Stage 6.30 recognizer ownership stays live from Player-Up into Question",withHarness(h=>{const s=h.api.getState(),recognizer=h.recognition(),count=FakeSpeechRecognition.instances.length;s.mode="original";s.players=[{id:"p1",name:"Alex"},{id:"p2",name:"Blair"}];h.api.startGame();let snap=h.window.__LOS_PLAYTEST_DIAGNOSTICS__.snapshot().recognition;assert.equal(s.screen,"handoff");assert.equal(snap.owner.screen,"handoff");assert.equal(h.recognition(),recognizer);h.timers.advance(3450);snap=h.window.__LOS_PLAYTEST_DIAGNOSTICS__.snapshot().recognition;assert.equal(s.screen,"question");assert.equal(snap.owner.screen,"question");assert.equal(snap.state,"listening");assert.equal(FakeSpeechRecognition.instances.length,count);h.speak(s.game.current.a,{final:true});assert.equal(s.screen,"result")}));

test("Stage 6.21 onerror and onend share one bounded restart",withHarness(h=>{const first=h.recognition(),count=FakeSpeechRecognition.instances.length;first.error("audio-capture");first.end();h.timers.advance(25);assert.equal(FakeSpeechRecognition.instances.length,count+1);h.timers.advance(2000);assert.equal(FakeSpeechRecognition.instances.length,count+1);const snap=h.window.__LOS_PLAYTEST_DIAGNOSTICS__.snapshot().recognition;assert.equal(snap.restartCount,1);assert.equal(snap.lastError,"audio-capture");assert.equal(snap.state,"listening")}));

test("Stage 6.21 recognition error watchdog recovers when mobile onend never arrives",withHarness(h=>{const first=h.recognition(),count=FakeSpeechRecognition.instances.length;first.error("network");h.timers.advance(199);assert.equal(h.recognition(),first);h.timers.advance(1);assert.equal(h.recognition(),null);h.timers.advance(25);assert.equal(FakeSpeechRecognition.instances.length,count+1);assert.equal(h.window.__LOS_PLAYTEST_DIAGNOSTICS__.snapshot().recognition.state,"listening");assert.ok(h.api.getVoiceDiagnostics().some(x=>x.stage==="recognition-error-end-timeout"&&x.error==="network"))}));

test("West Coast safe exact interim answers score immediately and finalization stays idempotent",withHarness(h=>{const s=activeQuestion(h);s.game.current={q:"What planet?",a:"Mars"};s.game.answered=false;h.speak("Mars",{final:false,confidence:.2});assert.equal(s.screen,"result");assert.equal(s.game.players[0].correct,1);assert.ok(h.api.getVoiceDiagnostics().some(x=>x.stage==="answer-interim-prevalidated"));const acceptedAt=s.game.answerAcceptedAt;h.speak("Mars",{final:true,confidence:.2});assert.equal(s.screen,"result");assert.equal(s.game.players[0].correct,1);assert.equal(s.game.answerAcceptedAt,acceptedAt)}));

test("Stage 6.37 phone voice-health HUD exposes enable-decision inputs",()=>{const h=createHarness({voiceHealth:true});try{const panel=h.document.getElementById("voiceHealthPanel"),text=panel?.textContent||"";assert.ok(panel);for(const value of ["6.38/current-generation-music-expansion","screen home","desired true","state listening","decision true · start-requested","setting true · stored unset","API SpeechRecognition · supported true · secure true","permissionBlocked false","owner home#0","interim:","final:","error:","suppressed:"])assert.match(text,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")))}finally{h.close()}});

test("Stage 6.24 distinguishes persisted Voice Off from missing Safari speech API",()=>{
 const off=createHarness({storage:{los5_voice:"false"},voiceHealth:true});try{const s=off.window.__LOS_PLAYTEST_DIAGNOSTICS__.snapshot().recognition;assert.equal(s.voiceSetting,false);assert.equal(s.storedVoiceSetting,"false");assert.equal(s.desired,false);assert.equal(s.suppressionReason,"voice-setting-off");assert.equal(s.lastDesiredDecision.reason,"voice-setting-off")}finally{off.close()}
 const unsupported=createHarness({speechApi:"none",voiceHealth:true});try{const state=activeQuestion(unsupported),s=unsupported.window.__LOS_PLAYTEST_DIAGNOSTICS__.snapshot().recognition;assert.equal(state.screen,"question");assert.equal(s.owner.screen,"question");assert.equal(s.voiceSetting,true);assert.equal(s.speechSupported,false);assert.equal(s.speechApi,"none");assert.equal(s.desired,false);assert.equal(s.suppressionReason,"speech-api-unavailable");assert.equal(s.lastDesiredDecision.reason,"speech-api-unavailable");assert.ok(unsupported.api.getVoiceDiagnostics().some(x=>x.stage==="recognition-stop-requested"&&x.reason==="speech-api-unavailable"))}finally{unsupported.close()}
 const webkit=createHarness({speechApi:"webkit",voiceHealth:true});try{const state=activeQuestion(webkit),s=webkit.window.__LOS_PLAYTEST_DIAGNOSTICS__.snapshot().recognition;assert.equal(state.screen,"question");assert.equal(s.owner.screen,"question");assert.equal(s.speechApi,"webkitSpeechRecognition");assert.equal(s.desired,true);assert.equal(s.state,"listening");assert.equal(s.lastDesiredDecision.reason,"start-requested")}finally{webkit.close()}
});
