"use strict";
const fs=require("node:fs"),path=require("node:path"),http=require("node:http");
const {chromium}=require("playwright");
const ROOT=path.resolve(__dirname,"..","..");
const VIEWPORTS=[[320,568,"small-phone-portrait"],[375,667,"iphone-se-portrait"],[390,844,"review-phone-portrait"],[393,852,"iphone-15-portrait"],[430,932,"large-phone-portrait"],[568,320,"small-phone-landscape"],[667,375,"iphone-se-landscape"],[844,390,"review-phone-landscape"],[852,393,"iphone-15-landscape"],[932,430,"large-phone-landscape"],[768,1024,"small-tablet-portrait"],[1024,768,"small-tablet-landscape"],[1024,1366,"large-tablet-portrait"],[1366,1024,"large-tablet-landscape"],[1366,768,"laptop"],[1440,900,"review-desktop"],[1920,1080,"desktop"],[2560,1440,"large-desktop"],[3840,2160,"tv-4k"]].map(([width,height,name])=>({width,height,name}));
const SCREENS=["home","setup","packs","mode","industry","difficulty","fun","players","time","ready","handoff","lock-in","question-ordinary","question","result-ordinary","result-timeout","standings-2","standings-8","standings-14","eliminated","result","result-unbroken","paused","quit","showdown","champion"];
const MIME={".css":"text/css",".js":"text/javascript",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".svg":"image/svg+xml",".webp":"image/webp",".woff2":"font/woff2",".json":"application/json",".webmanifest":"application/manifest+json"};
let assetOriginPromise;
function assetOrigin(){
 if(assetOriginPromise)return assetOriginPromise;
 assetOriginPromise=new Promise((resolve,reject)=>{const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,"http://127.0.0.1").pathname);if(pathname==="/__responsive_harness__.html"){res.writeHead(200,{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store"});res.end('<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><link rel="icon" href="data:,"><link rel="stylesheet" href="/app.css"></head><body><main id="app"></main></body></html>');return}if(pathname==="/__los_build_proof"){res.writeHead(200,{"Content-Type":"application/json","Cache-Control":"no-store"});res.end(JSON.stringify({repoPath:ROOT,branch:"responsive-harness",head:"working-tree",sha256:{}}));return}const target=path.resolve(ROOT,"."+pathname);if(!target.startsWith(ROOT+path.sep)){res.writeHead(403);res.end("Forbidden");return}fs.stat(target,(error,stat)=>{if(error||!stat.isFile()){res.writeHead(404);res.end("Not found");return}res.writeHead(200,{"Content-Type":MIME[path.extname(target).toLowerCase()]||"application/octet-stream","Content-Length":stat.size,"Cache-Control":"no-store"});fs.createReadStream(target).pipe(res)})});server.once("error",reject);server.listen(0,"127.0.0.1",()=>{server.unref();resolve(`http://127.0.0.1:${server.address().port}`)})});return assetOriginPromise
}
function instrument(source){const marker="})();",at=source.lastIndexOf(marker),expose=`\nObject.assign(globalThis.__RESPONSIVE__,{state,home,setup,packs,mode,industry,difficulty,fun,players,time,ready,handoff,playerUpCountdown,transition,question,result,showCurrentStandings,pauseGame,confirmEnd,showdownIntro,champion,stopVoice,clearRuntime});\n`;return source.slice(0,at)+expose+source.slice(at)}
async function launch(){
 const bundled=path.join(process.env.LOCALAPPDATA||"","ms-playwright","chromium-1234","chrome-win64","chrome.exe");
 return chromium.launch({headless:true,...(fs.existsSync(bundled)?{executablePath:bundled}:{})})
}
async function createPage(browser,viewport){
 const page=await browser.newPage({viewport:{width:viewport.width,height:viewport.height},deviceScaleFactor:1,reducedMotion:"reduce"});
 const diagnostics={requestFailed:[],httpErrors:[],consoleErrors:[],pageErrors:[]};page.__visualAssetDiagnostics=diagnostics;
 page.on("requestfailed",request=>diagnostics.requestFailed.push({url:request.url(),error:request.failure()?.errorText||"request failed"}));page.on("response",response=>{if(response.status()===403||response.status()===404)diagnostics.httpErrors.push({url:response.url(),status:response.status()})});page.on("console",message=>{if(message.type()==="error")diagnostics.consoleErrors.push({text:message.text(),url:message.location().url||""})});page.on("pageerror",error=>diagnostics.pageErrors.push(error.message));
 await page.goto((await assetOrigin())+"/__responsive_harness__.html",{waitUntil:"networkidle"});
 await page.evaluate(viewport=>{const data=new Map([["los5_voice","false"]]);Object.defineProperty(window,"localStorage",{value:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k),clear:()=>data.clear()}});if(viewport.usableHeight){const vv={width:viewport.width,height:viewport.usableHeight,offsetTop:viewport.usableOffsetTop??Math.max(0,(viewport.height-viewport.usableHeight)/2),offsetLeft:0,scale:1,pageTop:0,pageLeft:0,addEventListener(){},removeEventListener(){}};Object.defineProperty(window,"visualViewport",{configurable:true,value:vv})}class AC{constructor(){this.currentTime=0;this.state="running";this.destination={}}createOscillator(){return{type:"",frequency:{setValueAtTime(){}},connect(){},start(){},stop(){}}}createGain(){return{gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){}}}resume(){}}window.AudioContext=AC;window.__RESPONSIVE__={}},viewport);
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank-data.js"),"utf8")});
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank-batch-1.js"),"utf8")});
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank-batch-2.js"),"utf8")});
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank-batch-3.js"),"utf8")});
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank-batch-4.js"),"utf8")});
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank-batch-5.js"),"utf8")});
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank-batch-6.js"),"utf8")});
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank-batch-7.js"),"utf8")});
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank-batch-8.js"),"utf8")});
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank-batch-9.js"),"utf8")});
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank-batch-10.js"),"utf8")});
 await page.addScriptTag({content:fs.readFileSync(path.join(ROOT,"question-bank.js"),"utf8")});
 await page.addScriptTag({content:instrument(fs.readFileSync(path.join(ROOT,"app.js"),"utf8"))});return page
}
async function verifyVisualAssets(page,{required=[],avatar=false}={}){
 const result=await page.evaluate(async({required,avatar})=>{const urls=new Set(),add=value=>{for(const match of String(value||"").matchAll(/url\(["']?([^"')]+)["']?\)/g))urls.add(new URL(match[1],document.baseURI).href)};for(const element of document.querySelectorAll("*")){add(getComputedStyle(element).backgroundImage);add(getComputedStyle(element,"::before").backgroundImage);add(getComputedStyle(element,"::after").backgroundImage)}const all=[...urls].filter(url=>url.includes("/assets/")),checks=[],bounded=(promise,label)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error(label+" timed out")),15000))]);for(const url of all){let status=0,decoded=false,error="";try{const image=new Image();image.src=url;await bounded(image.decode(),"decode");decoded=image.naturalWidth>0&&image.naturalHeight>0;status=decoded?200:0;if(!decoded)throw new Error("decoded image has no dimensions")}catch(cause){error=String(cause?.message||cause)}checks.push({url,status,decoded,error})}const missing=required.filter(pattern=>!checks.some(check=>check.url.includes(pattern)&&check.status===200&&check.decoded)),avatarStyle=[...document.querySelectorAll(".los-avatar-art")].map(element=>getComputedStyle(element).backgroundImage).find(value=>value&&value!=="none")||"";return{origin:location.origin,checks,missing,decodeFailures:checks.filter(check=>!check.decoded||check.status!==200),avatarMissing:avatar&&!avatarStyle.includes("/assets/")}}, {required,avatar});return{...result,network:page.__visualAssetDiagnostics}
}
async function show(page,name){
 const requested=name;
 if(name==="question-ordinary")name="question";
 if(name==="result-ordinary"||name==="result-timeout"||name==="result-unbroken"||name.startsWith("standings-"))name="result";
 await page.evaluate(()=>document.getElementById("pauseOverlay")?.remove());
 await page.evaluate(name=>{const a=window.__RESPONSIVE__,s=a.state;a.clearRuntime();s.voiceOn=false;s.readQuestions=true;s.mode="original";s.quick=false;s.duration=15;s.questionSeconds=15;s.difficulty="medium";s.categories=[];s.industry="Healthcare";s.players=[{id:"p1",name:"Alexandria Montgomery-Washington"},{id:"p2",name:"Blair"},{id:"p3",name:"Casey"},{id:"p4",name:"Devon"},{id:"p5",name:"Emerson"},{id:"p6",name:"Frankie"}];const game=()=>({players:s.players.map(p=>({...p,correct:12,wrong:1,timeout:0,strikes:p.id==="p1"?2:1,eliminated:false})),startingCount:6,idx:0,qnum:8,used:[],current:{q:"Which internationally recognized scientific achievement transformed how people understand the natural world across generations?",a:"The theory of evolution by natural selection"},answered:false,started:Date.now(),speechLog:[],lastSpeechLog:[],showdown:false,lastOutcomeDetail:""});s.game=null;if(["home","setup","mode","industry","difficulty","fun","players","time","ready"].includes(name)){s.screen=name;a[name]();return}s.game=game();if(name==="handoff")a.handoff();else if(name==="lock-in")a.transition("question",()=>{});else if(name==="question")a.question(true);else if(name==="result"){s.game.answered=true;a.result("wrong")}else if(name==="paused"){a.question(true);a.pauseGame()}else if(name==="quit"){a.question(true);a.pauseGame();a.confirmEnd()}else if(name==="showdown")a.showdownIntro();else if(name==="champion")a.champion(s.game.players[0])},name);
 if(name==="handoff")await page.evaluate(()=>window.__RESPONSIVE__.playerUpCountdown("p1",false));
 if(name==="eliminated")await page.evaluate(()=>{const a=window.__RESPONSIVE__,s=a.state;s.game.players[0].name="Alexandria Montgomery-Washington";s.game.players[0].avatar="street-nightcap";s.game.players[0].strikes=3;s.game.players[0].eliminated=true;a.transition("elimination",()=>{})});
 if(name==="lock-in")await page.evaluate(()=>window.__RESPONSIVE__.transition("lockIn",()=>{}));
 if(requested!==name)await page.evaluate(requested=>{const a=window.__RESPONSIVE__,s=a.state;if(requested==="question-ordinary"){s.game.current={q:"What planet is known as the Red Planet?",a:"Mars"};s.game.answered=false;a.question(true)}else if(requested==="result-ordinary"){s.game.players=s.game.players.slice(0,3);s.game.current={q:"What planet?",a:"Mars"};s.game.answered=true;a.result("correct")}else if(requested==="result-timeout"){s.game.players=s.game.players.slice(0,3);s.game.current={q:"What planet?",a:"Mars"};s.game.players[0].strikes=1;s.game.answered=true;a.result("timeout")}else if(requested.startsWith("standings-")){const count=Number(requested.split("-")[1]);s.game.players=Array.from({length:count},(_,i)=>({id:`p${i+1}`,name:i===count-1?"Alexandria Montgomery-Washington":i===count-2?"Christopher Robin":`Player ${i+1}`,avatar:["wc-a1","street-nightcap","senior-glasses","silhouette"][i%4],correct:i,wrong:0,timeout:0,strikes:i%4,eliminated:i%4===3}));s.game.startingCount=count;s.game.current={q:"What planet?",a:"Mars"};s.game.answered=true;a.result("timeout");a.showCurrentStandings(s.game)}else if(requested==="result-unbroken"){s.game.current={q:"Name the fictional compound.",a:"Pneumonoultramicroscopicsilicovolcanoconiosis"};s.game.answered=true;a.result("wrong")}},requested);
 await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))
}
async function measure(page){return page.evaluate(()=>{const vw=innerWidth,vh=innerHeight,body=document.body,root=document.documentElement,rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}},visible=e=>{const cs=getComputedStyle(e),r=e.getBoundingClientRect();return cs.display!=="none"&&cs.visibility!=="hidden"&&r.width>0&&r.height>0},controls=[...document.querySelectorAll("button,input")].filter(visible).map(e=>({label:(e.textContent||e.getAttribute("aria-label")||e.type).trim(),...rect(e)})),clipped=[...document.querySelectorAll(".topbar,.content,.footer,.game-topbar,.question-text,.timer,.handoff-player-name,.answer-panel,.standings,.pause-card,.showdown-stage,.complete-stage,.los-home-layout,.los-roster")].filter(visible).map(e=>({selector:e.className,...rect(e)})).filter(r=>r.x<-.5||r.y<-.5||r.right>vw+.5||r.bottom>vh+.5),footer=document.querySelector(".footer"),content=document.querySelector(".content"),q=document.querySelector(".question-text"),timer=document.querySelector(".timer"),overlap=(a,b)=>a&&b&&a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top,primary=[...document.querySelectorAll(".grid,.category-grid,.industry-grid,.difficulty-grid,.los-home-layout,.los-player-grid,.los-avatar-grid,.ready-card,.wc-showtime-live,.question-text,.result-body,.transition-copy,.handoff,.showdown-stage,.complete-stage")].find(visible),pr=primary?.getBoundingClientRect();return{horizontalOverflow:Math.max(body.scrollWidth,root.scrollWidth)-vw,verticalDocumentOverflow:Math.max(body.scrollHeight,root.scrollHeight)-vh,footer:footer?rect(footer):null,footerVisible:!footer||((r=>r.top>=0&&r.bottom<=vh)(footer.getBoundingClientRect())),undersizedControls:controls.filter(c=>c.width<44||c.height<44),clipped,contentScroll:content?{client:content.clientHeight,scroll:content.scrollHeight,overflow:getComputedStyle(content).overflowY}:null,timerOverlap:overlap(q?.getBoundingClientRect(),timer?.getBoundingClientRect()),primaryWidthRatio:pr?pr.width/vw:null,primaryHeightRatio:pr?pr.height/vh:null,controls}})}
module.exports={VIEWPORTS,SCREENS,launch,createPage,show,measure,verifyVisualAssets,assetOrigin,instrument};
